name: weather_app
description: Weather app
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  dio: ^4.0.6
  json_annotation: ^4.6.0
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  retrofit: ^3.0.1+1
  injectable: ^1.5.3
  flutter_dotenv: ^5.0.2
  dartz: ^0.10.1
  connectivity_plus: ^2.3.6+1
  google_fonts: ^3.0.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  retrofit_generator: ^4.0.3
  injectable_generator: ^1.5.4

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
